#ifndef _H_D__HotPot_include_hotpot_hp_config_hd_TYPES
#define _H_D__HotPot_include_hotpot_hp_config_hd_TYPES
/**
 * Autogenerated by HotPot (0.0.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "hotpot/hp_platform.h"
#define	HOTPOT_VERSION "0.0.1"
#endif//_H_D__HotPot_include_hotpot_hp_config_hd_TYPES
