/**
 * Autogenerated by HotScript (0.0.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#ifndef _H_hoterror_hp_error_msg_hd_READER
#define _H_hoterror_hp_error_msg_hd_READER
#include "hotpot/hp_platform.h"
#include "hotpot/hp_error_code.h"
#include "hotprotocol/hp_abstract_reader.h"
#include <string.h>
#include "hotpot/hp_error_code.h"
#include "hoterror/hp_error_msg.h"
HP_ERROR_CODE read_HP_ERROR_MSG(HPAbstractReader *self, HP_ERROR_MSG *data);
HP_ERROR_CODE read_HP_ERROR_MSG_LIBRARY(HPAbstractReader *self, HP_ERROR_MSG_LIBRARY *data);
#endif//_H_hoterror_hp_error_msg_hd_READER
