find_program(HOTDATA_EXECUTABLE hotdata
	PATHS $ENV{HOTPOT_DIR}/bin
   )

find_path(HOTPOT_INCLUDE_DIR NAMES hotplatform/hp_platform.h
	PATHS $ENV{HOTPOT_DIR}/include
   )

find_library(HOTLIB_LIBRARIES NAMES hotlib
	PATHS $ENV{HOTPOT_DIR}/lib
   )

find_library(HOTPROTOCOL_LIBRARIES NAMES hotprotocol
	PATHS $ENV{HOTPOT_DIR}/lib
   )

find_library(HOTSCRIPT_LIBRARIES NAMES hotscript
	PATHS $ENV{HOTPOT_DIR}/lib
   )

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HotPot  DEFAULT_MSG
	HOTLIB_LIBRARIES HOTPROTOCOL_LIBRARIES HOTSCRIPT_LIBRARIES HOTPOT_INCLUDE_DIR HOTDATA_EXECUTABLE)

mark_as_advanced(HOTLIB_LIBRARIES HOTPROTOCOL_LIBRARIES HOTSCRIPT_LIBRARIES HOTPOT_INCLUDE_DIR HOTDATA_EXECUTABLE)
