find_program(HOTDATA_EXECUTABLE hd
	PATHS $ENV{HOTPOT_DIR}/bin
   )

find_program(HOTSCRIPT_EXECUTABLE hs
	PATHS $ENV{HOTPOT_DIR}/bin
   )

find_path(HOTPOT_INCLUDE_DIR NAMES hotpot/hp_platform.h
	PATHS $ENV{HOTPOT_DIR}/include
   )

find_library(HOTPOT_LIBRARIES NAMES hotpot
	PATHS $ENV{HOTPOT_DIR}/lib
   )

find_library(HOTPROTOCOL_LIBRARIES NAMES hotprotocol
	PATHS $ENV{HOTPOT_DIR}/lib
   )

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HotPot  DEFAULT_MSG
                                  HOTPOT_LIBRARIES HOTPROTOCOL_LIBRARIES HOTPOT_INCLUDE_DIR HOTDATA_EXECUTABLE HOTSCRIPT_EXECUTABLE)

mark_as_advanced(HOTPOT_LIBRARIES HOTPROTOCOL_LIBRARIES HOTPOT_INCLUDE_DIR HOTDATA_EXECUTABLE HOTSCRIPT_EXECUTABLE)
