/**
 * Autogenerated by HotData (0.0.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#ifndef _H_hotlib_hp_config_hd_WRITER_HEADER
#define _H_hotlib_hp_config_hd_WRITER_HEADER
#include "hotplatform/hp_platform.h"
#include "hotlib/hp_error_code.h"
#include "hotprotocol/hp_abstract_writer.h"
#include "hotlib/hp_config.h"
HP_ERROR_CODE write_hpbool_name(HPAbstractWriter *self, hpbool data);
HP_ERROR_CODE write_hpbool_number(HPAbstractWriter *self, hpbool data);
HP_ERROR_CODE write_hpbool(HPAbstractWriter *self, hpbool data);
HP_ERROR_CODE write_HPType_name(HPAbstractWriter *self, HPType data);
HP_ERROR_CODE write_HPType_number(HPAbstractWriter *self, HPType data);
HP_ERROR_CODE write_HPType(HPAbstractWriter *self, HPType data);
#endif//_H_hotlib_hp_config_hd_WRITER_HEADER
