/**
 * Autogenerated by HotData (0.0.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#ifndef _H_hotlib_hp_config_hd_WRITER_HEADER
#define _H_hotlib_hp_config_hd_WRITER_HEADER
#include "platform/tlibc_platform.h"
#include "hotlib/hp_error_code.h"
#include "protocol/tlibc_abstract_writer.h"
#include "hotlib/hp_config.h"
TLIBC_ERROR_CODE write_HPType_name(TLIBC_ABSTRACT_WRITER *self, HPType data);
TLIBC_ERROR_CODE write_HPType_number(TLIBC_ABSTRACT_WRITER *self, HPType data);
TLIBC_ERROR_CODE write_HPType(TLIBC_ABSTRACT_WRITER *self, HPType data);
#endif//_H_hotlib_hp_config_hd_WRITER_HEADER
