/**
 * Autogenerated by HotData (0.0.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#ifndef _H_hotlib_hp_error_msg_hd_READER_HEADER
#define _H_hotlib_hp_error_msg_hd_READER_HEADER
#include "hotplatform/hp_platform.h"
#include "hotlib/hp_error_code.h"
#include "hotprotocol/hp_abstract_reader.h"
#include "hotlib/hp_error_msg.h"
#include "hotlib/hp_error_code_reader.h"
HP_ERROR_CODE read_HP_ERROR_MSG(HPAbstractReader *self, HP_ERROR_MSG *data);
HP_ERROR_CODE read_HP_ERROR_MSG_LIBRARY(HPAbstractReader *self, HP_ERROR_MSG_LIBRARY *data);
#endif//_H_hotlib_hp_error_msg_hd_READER_HEADER
