#ifndef _H_GLOBALS
#define _H_GLOBALS

//文件描述的扩展名
#define DATA_DESCRIPTION_FILE_EXTENSION_NAME ".hd"
#define HOTPOT_VERSION "0.0.1"
#define HP_INVALID_INDEX 4294967295
#define MAX_IDENTIFIER_LENGTH 128



#endif//_H_GLOBALS
