/**
 * Autogenerated by HotData (0.0.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#ifndef _H_hotlib_hp_config_hd_TYPES
#define _H_hotlib_hp_config_hd_TYPES
#include "platform/tlibc_platform.h"
#define HOTPOT_VERSION "0.0.1"
#define HP_INVALID_INDEX 4294967295
#define MAX_IDENTIFIER_LENGTH 128

#endif//_H_hotlib_hp_config_hd_TYPES
